SCENARIO = [
    "Bitmoji",
    "Amazon Seller",
    "WhatsApp",
    "Candy Crush Jelly",
    "Candy Crush Saga",
    "NYT Games",
    "Simple PDF Reader",
    "Crossy Road",
    "FaceApp",
    "Lyft",
    "Pou",
    "Hide 'N Seek!",
    "Telegram",
    "Signal",
    "Kindle",
    "Firefox",
    "Coinbase",
    "Candy Crush Soda",
    "Kids Transport",
    "Hill Climb Racing",
    "Call Recorder",
    "Kik",
    "Color Fill 3D",
    "Etsy",
    "Pi",
    "Soccer Star",
    # "Puffin Cloud Browser",
    "Puffin",
    "Crunchyroll",
    "VLC",
    "eToro",
    "GroupMe",
    "DNA Evolution 3D"
]
